# Generated by Django 4.2.4 on 2024-02-23 15:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.TextField(default='Best friends don’t let you do stupid things alone.', max_length=300)),
                ('about_yourself', models.TextField(default='😀', max_length=160)),
                ('profile_pic', models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')),
                ('q1', models.TextField(default='No answer yet.', max_length=1000)),
                ('q2', models.TextField(default='No answer yet.', max_length=1000)),
                ('q3', models.TextField(default='No answer yet.', max_length=1000)),
                ('q4', models.TextField(default='No answer yet.', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileBulletinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
