# Generated by Django 4.2.4 on 2024-02-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profilebulletinboard_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebulletinboard',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
