# Generated by Django 5.0.2 on 2024-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_followerscount_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerscount',
            name='follower',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='followerscount',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
