# Generated by Django 5.0.2 on 2024-03-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_followerscount_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='post_id',
        ),
        migrations.AddField(
            model_name='likepost',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.bulletinboard'),
        ),
    ]
