# Generated by Django 5.0.2 on 2024-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_bulletinboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
