# Generated by Django 5.0.2 on 2024-03-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_bulletinboard_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='image',
            field=models.ImageField(default=None, upload_to='announcement_pics'),
        ),
    ]
