# Generated by Django 5.0.2 on 2024-03-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_bulletinboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_pics'),
        ),
    ]
