# Generated by Django 5.0.2 on 2024-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_bulletinboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinboard',
            name='image',
            field=models.ImageField(default='read-me.jpg', upload_to='announcement_pics'),
        ),
    ]
