# Generated by Django 5.0.2 on 2024-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
