# Generated by Django 5.0.2 on 2024-03-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profilebulletinboard_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
