# Generated by Django 5.0.2 on 2024-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='read-me.jpg', upload_to='announcement_pics'),
        ),
    ]
