# Generated by Django 5.0.2 on 2024-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='add_image_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_pics'),
        ),
    ]
