# Generated by Django 5.0.2 on 2024-03-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_add_image_caption_blog_additional_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='add_image_caption',
            new_name='image10_caption',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='additional_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image4_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image5_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image6_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image7_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image8_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image9_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='read-me.jpg', upload_to='blog_pics'),
        ),
    ]
