# Generated by Django 5.0.2 on 2024-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_content10_blog_content2_blog_content3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image2_caption',
            new_name='image_end_caption',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_end',
            field=models.ImageField(default='read-me.jpg', upload_to='blog_pics'),
        ),
    ]
