# Generated by Django 5.0.2 on 2024-03-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_image2_caption_blog_image_end_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image10_caption',
            new_name='image2_caption',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image10',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_end',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
    ]
