# Generated by Django 5.0.2 on 2024-03-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_image10_caption_blog_image2_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image2_caption',
            field=models.CharField(default='Photo has no caption', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image3_caption',
            field=models.CharField(default='Photo has no caption', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image4_caption',
            field=models.CharField(default='Photo has no caption', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image5_caption',
            field=models.CharField(default='Photo has no caption', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image6_caption',
            field=models.CharField(default='Photo has no caption', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image7_caption',
            field=models.CharField(default='Photo has no caption', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image8_caption',
            field=models.CharField(default='Photo has no caption', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image9_caption',
            field=models.CharField(default='Photo has no caption', max_length=255),
        ),
    ]
