# Generated by Django 5.0.2 on 2024-03-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_image2_caption_alter_blog_image3_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='teaser',
            field=models.TextField(default='Read me...'),
        ),
    ]
