# Generated by Django 5.0.2 on 2024-03-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blog_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='teaser',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
