# Generated by Django 5.0.2 on 2024-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blog_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('music', 'Music'), ('personal', 'Personal'), ('promotions', 'Promotions'), ('travels', 'Travels'), ('others', 'Others')], default='education', max_length=50),
        ),
    ]
