# Generated by Django 5.0.2 on 2024-03-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
