# Generated by Django 5.0.2 on 2024-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_comment_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='featured',
        ),
        migrations.AddField(
            model_name='blog',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
